# Generated by Django 3.2.14 on 2023-10-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register1',
            name='language',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
